HW6
se-barabash/HW pull request #11
Opened 2024-12-04 14:10 UTC by se-barabash

2024-12-04 14:20 UTC, se-barabash commented on HW6.html
> +         // addThemAll(2, 4), addThemAll(1, 2, 3, 4), addThemAll(5, 5, 10)
умова задачі вимагає використати оператор розширення, але у консолі функція не має об'єкта , аби застосувати до нього оператор розширення: `console.log(addThemAll(2,4))`

2024-12-04 14:31 UTC, se-barabash commented on HW6.html
> +         // byProperty('runningTimeInMinutes', '>')
це поки чернетка, бо не відповідає кінцевим умовам задачі виведення інформації (пам'ятаю ваш наголос не міняти умови будь-якої задачі), але розв'язок правильний, а питаннячко таке: чи тут потрібні якісь оператори аля-розширенні та тому подібне, адже доволі просто все вийшло

2024-12-04 14:35 UTC, se-barabash commented on HW6.html
> +</html>
як можна видалити `HW2.html` та `HW3.html`, які в поточній домашці притаїлись пустими і непотрібними, яких в терміналові немає, коли відправляв з ПК сюди, на ґітгаба?

2024-12-06 15:56 UTC, myroslav-kolomiiets requested changes

2024-12-06 15:56 UTC, myroslav-kolomiiets commented on HW6.html
> +         // // задача 1 (2)
В умові задачі не вказано, що розв'язати потрібно двома, або більше, варіантами. Тому залиште тут те рішення, що йде на перевірку. Лишнє видаліть.

2024-12-06 15:56 UTC, myroslav-kolomiiets commented on HW6.html
> +         // const multiply = (a) => (b) => console.log(a * b)
Вірно

2024-12-06 15:56 UTC, myroslav-kolomiiets commented on HW6.html
> +               if (direction === '<') {
Опція зростання реалізована, а опція спадання? Фактично зараз можна що завгодно передати в direction, крім символу '<', і це буде спадання. Має бути чітко і те і те, і додана умова на випадок передачі не валідного значення в direction

2024-12-06 15:56 UTC, myroslav-kolomiiets commented on HW6.html
> +         // console.log(Array.from(new Set(userNames))) // 4.2
В умові сказано зробити два варіанти?

2024-12-06 15:59 UTC, myroslav-kolomiiets requested changes

2024-12-06 15:59 UTC, myroslav-kolomiiets commented on HW6.html
> +         // byProperty('runningTimeInMinutes', '>')
Ні, оператори розширення та тому подібні не потрібні. Потрібно не міняти умови задачі.

2024-12-06 15:59 UTC, myroslav-kolomiiets requested changes

2024-12-06 15:59 UTC, myroslav-kolomiiets commented on HW6.html
> +         // console.table(movies.sort(byProperty('releaseYear', '<')))
Повертаючись до умов задачі, навіщо тут table?

2024-12-14 14:36 UTC, myroslav-kolomiiets approved these changes
Зараз все вірно. Роботу здано.

2024-12-14 14:36 UTC, merged