HW8
se-barabash/HW pull request #12
Opened 2024-12-10 20:58 UTC by se-barabash

2024-12-10 21:02 UTC, se-barabash commented on HW8.html
> +         padding: 10px;
чому margin box-sizing: border-box не працюють, аби правий кордон відмежовувався на задані величини, як ліворуч (я про вигляд HTML сторінку)?

2024-12-14 14:31 UTC, myroslav-kolomiiets requested changes

2024-12-14 14:31 UTC, myroslav-kolomiiets commented on HW8.html
> +         const wholeSection = document.querySelector('.firstSection h2')
querySelector використано три рази, а по умові:

> Кожен селектор має бути унікальним (тобто всі мають бути створені за допомогою різних методів) і має бути присвоєний якійсь змінній.

2024-12-14 14:31 UTC, myroslav-kolomiiets commented on HW8.html
> +         // title.innerHTML = 'привіт-привіт!'
В ДЗ не має бути лишнього коду, коментарів, тощо.

2025-01-01 15:04 UTC, se-barabash commented on HW8.html
> +         _4 = document.getElementsByClassName('hatredLevelBlock')[0]
гадаю, робота відповідає усім критеріям, аби ви її зарахували, але питання крутиться в голові і ніде не можу знайти відповіді: чи мається якась конструкція (а я колись, здається, бачив  її), де наявне слово 'Node', замість використовувати `query…` чи `getElement…`? 

це питання стосовно ширшої вибірки способів поклику на ці ж ноди, якщо правильно вжив це слово (нода)

2025-01-01 15:05 UTC, se-barabash commented on HW8.html
> +               <li>Пункт 5</li>
гадаю, робота відповідає усім критеріям, аби ви її зарахували, але питання крутиться в голові і ніде не можу знайти відповіді: чи мається якась конструкція (а я колись, здається, бачив її), де наявне слово 'Node', замість використовувати query… чи getElement…?

це питання стосовно ширшої вибірки способів поклику на ці ж ноди, якщо правильно вжив це слово (нода)

2025-01-01 15:05 UTC, se-barabash commented on HW8.html
>        </script>
гадаю, робота відповідає усім критеріям, аби ви її зарахували, але питання крутиться в голові і ніде не можу знайти відповіді: чи мається якась конструкція (а я колись, здається, бачив її), де наявне слово 'Node', замість використовувати query… чи getElement…?

це питання стосовно ширшої вибірки способів поклику на ці ж ноди, якщо правильно вжив це слово (нода)

2025-01-12 08:24 UTC, myroslav-kolomiiets requested changes

2025-01-12 08:24 UTC, myroslav-kolomiiets commented on HW8.html
> +         _2 = document.querySelectorAll('section h2')[0]
змінна _2 і нижче, не об'явлена, відсутні ; між рядками коду

у вас же 'use strict' вище, невже редактор не показує що у вас Unresolved variable or type _2 ?

2025-01-19 11:19 UTC, myroslav-kolomiiets requested changes

2025-01-19 11:19 UTC, myroslav-kolomiiets commented on HW8.html
> +            _2 = document.querySelectorAll('section h2')[0],
```suggestion
           **тут має бути ключове слово const** **тут має бути нормальна назва змінної** = document.querySelectorAll('section h2')[0] тут має бути **;**
```
І так всюди і завжди.

2025-01-22 20:58 UTC, myroslav-kolomiiets approved these changes

2025-01-23 05:19 UTC, merged